### ISSUE TITLE
uninitialized constant S3Relay::PrivateUrl::Addressable

### ISSUE THREAD

**Issue by mejibyte** [kjohnston/s3_relay#18] opened 2017-07-30 03:16 UTC
I'm trying to get s3_relay running on Rails 5.1 and getting an `POST /s3_relay/uploads`. Full stack trace below:

```
Started POST "/s3_relay/uploads" for ::1 at 2017-07-29 20:11:48 -0500
Processing by S3Relay::UploadsController#create as */*
  Parameters: {"parent_type"=>"thing", "parent_id"=>"1", "association"=>"photo_uploads", "uuid"=>"36cb2295-0f0c-424f-834a-5b7b229a9697", "filename"=>"GOPR1273.JPG", "content_type"=>"image/jpeg", "public_url"=>"https://[redacted].s3-us-west-2.amazonaws.com/37cb2295-0e0c-414f-834a-5b7b229a9597%2FGOPR1273.JPG"}
  Thing Load (0.1ms)  SELECT  "things".* FROM "things" WHERE "things"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
   (0.2ms)  begin transaction
  S3Relay::Upload Exists (0.2ms)  SELECT  1 AS one FROM "s3_relay_uploads" WHERE "s3_relay_uploads"."uuid" = ? LIMIT ?  [["uuid", "<36 bytes of binary data>"], ["LIMIT", 1]]
  SQL (4.0ms)  INSERT INTO "s3_relay_uploads" ("uuid", "parent_type", "parent_id", "upload_type", "filename", "content_type", "state", "pending_at", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["uuid", "<36 bytes of binary data>"], ["parent_type", "Thing"], ["parent_id", 1], ["upload_type", "PhotoUpload"], ["filename", "GOPR1273.JPG"], ["content_type", "image/jpeg"], ["state", "pending"], ["pending_at", "2017-07-30 03:11:48.800299"], ["created_at", "2017-07-30 03:11:48.803264"], ["updated_at", "2017-07-30 03:11:48.803264"]]
   (2.0ms)  commit transaction
Completed 500 Internal Server Error in 44ms (ActiveRecord: 6.8ms)


  
NameError (uninitialized constant S3Relay::PrivateUrl::Addressable):
  
s3_relay (0.6.0) lib/s3_relay/private_url.rb:7:in `initialize'
s3_relay (0.6.0) app/models/s3_relay/upload.rb:44:in `new'
s3_relay (0.6.0) app/models/s3_relay/upload.rb:44:in `private_url'
s3_relay (0.6.0) app/controllers/s3_relay/uploads_controller.rb:15:in `create'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
railties (5.1.2) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.2) lib/rails/railtie.rb:185:in `method_missing'
actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
rack (2.0.3) lib/rack/handler/webrick.rb:86:in `service'

::1 - - [29/Jul/2017:20:11:48 PDT] "POST /s3_relay/uploads HTTP/1.1" 500 11790
http://localhost:3000/things/1/edit -> /s3_relay/uploads
```

**Comment by andmej** [comment] 2017-07-30 03:17
@spovich 
perhaps caused by your changes in https://github.com/kjohnston/s3_relay/pull/16/commits/744906cd2526ac09856b6b2f225d83d98e1208eb?

**Comment by spovich** [comment] 2017-07-30 19:05
@andmej we are using this fine in production on a Rails 5.1 project.  From the error message, it appears that it is not finding `addressable`, but it is a runtime dependency: https://github.com/kjohnston/s3_relay/blob/master/s3_relay.gemspec#L21  So, maybe you need to re-bundle?  Check your `Gemfile.lock` for `addressable`.

**Comment by ctmaloney** [comment] 2017-12-08 19:42
@spovich also seeing this issue.  Had to add the require back in from https://github.com/kjohnston/s3_relay/commit/f2cb06dc6212d3743bf800250eb6b2b205ec90e8 to get it to work for me.

**Comment by artemf** [comment] 2018-06-12 22:31
The same error here with a clean new 5.1 rails project. Fixed by creating
_config/initializers/buggy_s3_relay_fix.rb_
```
require 'addressable'
```

**Closed** 2020-11-29 23:19 UTC

**Comment by yunixon** [comment] 2021-08-10 11:30
same issue
rails 5.2
s3_relay 0.7.0

**Comment by kjohnston** [comment] 2021-08-10 14:36
@yunixon, I was able to upgrade an app to 5.2 recently and did not run into this issue.  Please see @spovich's comment above about ensuring your `Gemfile.lock` is pulling in the `addressable` runtime dependency defined by `s3_relay`.  If that doesn't work, try @artemf's workaround.  I'll be discontinuing support for `s3_relay` as ActiveStorage now provides a more robust golden path solution, so when you get the chance to make the switch please do.  I'm down to just one app relying on this gem at this point, but won't be moving it over immediately.
